/************** TABLAS PARA EJERCICIOS ONE-TO-ONE ***************/
CREATE SEQUENCE usuarios_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE datos_usuarios_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE datos_usuarios(
   id INT GENERATED BY DEFAULT AS SEQUENCE datos_usuarios_id_seq,
   biografia CLOB,
   fecha_registro DATE,PRIMARY KEY(id)
);

CREATE TABLE usuarios(
   id INT GENERATED BY DEFAULT AS SEQUENCE usuarios_id_seq,   
   datos_autor_id INT,
   nombre VARCHAR(600),
   email VARCHAR(500),
   password VARCHAR(500),
   rol VARCHAR(500),
   activo BOOLEAN,
   PRIMARY KEY(id),
   FOREIGN KEY(datos_autor_id) REFERENCES datos_usuarios
);


/************** TABLAS PARA EJERCICIO ONE-TO-MANY ***************/
CREATE SEQUENCE articulo_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE comentario_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE articulos(
   id INT GENERATED BY DEFAULT AS SEQUENCE articulo_id_seq,
   usuario_id INT, 
   titulo VARCHAR(500), 
   contenido CLOB, 
   fecha_creacion DATE, 
   PRIMARY KEY(id), 
   FOREIGN KEY(usuario_id) REFERENCES usuarios
);

CREATE TABLE comentarios(
   id INT GENERATED BY DEFAULT AS SEQUENCE comentario_id_seq,
   articulo_id INT,
   comentario CLOB,
   comentarista VARCHAR(500),
   fecha_creacion DATE,
   PRIMARY KEY (id),
   FOREIGN KEY(articulo_id) REFERENCES articulos
);

/************** TABLAS PARA EJERCICIO MANY-TO-MANY ***************/
CREATE SEQUENCE categoria_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE categorias(
   id INT GENERATED BY DEFAULT AS SEQUENCE categoria_id_seq ,
   nombre VARCHAR(200),
   PRIMARY KEY(id)
);

CREATE TABLE categorias_articulos(
   categoria_id INT ,
   articulo_id INT,
   PRIMARY KEY(categoria_id, articulo_id),
   FOREIGN KEY(categoria_id) REFERENCES categorias,
   FOREIGN KEY(articulo_id) REFERENCES articulos
);

CREATE SEQUENCE departamento_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE departamentos(
   id INT GENERATED BY DEFAULT AS SEQUENCE departamento_id_seq ,
   nombre VARCHAR(200),
   PRIMARY KEY(id)
);

CREATE TABLE departamentos_usuarios(
   departamento_id INT,
   usuario_id INT,
   PRIMARY KEY(departamento_id, usuario_id),
   FOREIGN KEY(departamento_id) REFERENCES departamentos,
   FOREIGN KEY(usuario_id) REFERENCES usuarios
);


/************** DATOS PARA EJERCICIOS ONE-TO-ONE ***************/

INSERT INTO datos_usuarios(id,biografia,fecha_registro) VALUES(DEFAULT,'Usuario ficticio 1 creado para el curso de XML', '2013-10-20');
INSERT INTO usuarios(id, datos_autor_id, nombre, email, password, rol, activo) VALUES(DEFAULT,1,'Juan Perez', 'juan@email.com','1234','ROLE_EDITOR',true);

INSERT INTO datos_usuarios(id,biografia,fecha_registro) VALUES(DEFAULT,'Usuario ficticio 2 creado para el curso de XML', '2013-10-20');
INSERT INTO usuarios(id, datos_autor_id, nombre, email, password,rol,activo) VALUES(DEFAULT,2,'Pepe', 'pepe@email.com','1234','ROLE_ADMIN',true);

/************** DATOS PARA EJERCICIO ONE-TO-MANY ***************/

INSERT INTO articulos VALUES(DEFAULT,1,'titulo articulo 1','contenido articulo 1','2013-10-24');
INSERT INTO articulos VALUES(DEFAULT,1,'titulo articulo 2','contenido articulo 2','2013-10-24');

INSERT INTO comentarios VALUES(DEFAULT, 1, 'mi comentario 1','anonimo','2013-9-24');
INSERT INTO comentarios VALUES(DEFAULT, 1, 'mi comentario 2','anonimo','2013-11-24');

/************** DATOS PARA EJERCICIO MANY-TO-MANY ***************/

INSERT INTO categorias VALUES(DEFAULT, 'java');
INSERT INTO categorias VALUES(DEFAULT, 'linux');
INSERT INTO categorias VALUES(DEFAULT, 'xml');

INSERT INTO categorias_articulos VALUES(1,1);
INSERT INTO categorias_articulos VALUES(2,1);
INSERT INTO categorias_articulos VALUES(3,1);

INSERT INTO categorias_articulos VALUES(1,2);
INSERT INTO categorias_articulos VALUES(2,2);


INSERT INTO departamentos VALUES(DEFAULT,'deportes');
INSERT INTO departamentos VALUES(DEFAULT,'tecnologia');
INSERT INTO departamentos VALUES(DEFAULT,'espectaculos');
INSERT INTO departamentos VALUES(DEFAULT,'ciencia');

INSERT INTO departamentos_usuarios(usuario_id,departamento_id) VALUES(1,1);
INSERT INTO departamentos_usuarios(usuario_id,departamento_id) VALUES(1,2);
INSERT INTO departamentos_usuarios(usuario_id,departamento_id) VALUES(1,3);

INSERT INTO departamentos_usuarios(usuario_id,departamento_id) VALUES(2,3);
INSERT INTO departamentos_usuarios(usuario_id,departamento_id) VALUES(2,4);
